"""DynamoDB data layer — boto3 sync client.

Table: ``aegis-enclave-executions`` (configurable via DYNAMODB_TABLE_NAME).
PK: ``execution_id`` (String, UUID4 generated by the API).

Connection:
    AWS_ENDPOINT_URL           — boto3 standard; overrides to local dynamodb-local.
    DYNAMODB_TABLE_NAME        — table name; default "aegis-enclave-executions".
    AWS_DEFAULT_REGION         — boto3 standard; default "eu-central-1".

TTL strategy (status-aware):
    queued / running  → no ttl_at set (do not auto-delete in-flight work)
    done              → ttl_at = completed_at + 30 days
    failed            → ttl_at = completed_at + 90 days

Idempotency:
    ``insert_queued_execution`` uses a ConditionExpression to reject duplicate
    inserts (attribute_not_exists(execution_id)).
    ``mark_running`` / ``mark_done`` / ``mark_failed`` use ConditionExpression
    on the previous status to prevent out-of-order updates.

Design rationale: ADR-0042.
"""

from __future__ import annotations

import os
import time
from decimal import Decimal
from typing import Any

import boto3
from boto3.dynamodb.conditions import Attr
from botocore.exceptions import ClientError

from prime_service.schemas import Status

_TABLE_NAME = os.environ.get("DYNAMODB_TABLE_NAME", "aegis-enclave-executions")

# TTL durations (seconds)
_TTL_DONE_DAYS = 30
_TTL_FAILED_DAYS = 90

_SECONDS_PER_DAY = 86_400


def _get_client() -> Any:
    """Return a boto3 DynamoDB resource (table accessor)."""
    endpoint_url = os.environ.get("AWS_ENDPOINT_URL")
    region = os.environ.get("AWS_DEFAULT_REGION", "eu-central-1")
    resource = boto3.resource(
        "dynamodb",
        endpoint_url=endpoint_url,
        region_name=region,
    )
    return resource.Table(_TABLE_NAME)


def _table() -> Any:
    """Lazily return the DynamoDB Table resource for the executions table."""
    return _get_client()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def insert_queued_execution(
    *,
    execution_id: str,
    range_start: int,
    range_end: int,
) -> str:
    """Write a new execution row in ``queued`` state.

    Uses ``attribute_not_exists(execution_id)`` ConditionExpression to make
    the insert idempotent — a retry of the same UUID4 is a no-op (the row
    already exists; the client receives a ConditionalCheckFailedException
    which is swallowed and the existing id is returned).

    Returns:
        execution_id (the same string that was passed in).

    Raises:
        ClientError (non-conditional) — propagated to the caller.
    """
    now_epoch = int(time.time())
    item: dict[str, Any] = {
        "execution_id": execution_id,
        "status": Status.queued.value,
        "range_start": Decimal(range_start),
        "range_end": Decimal(range_end),
        "created_at": Decimal(now_epoch),
    }
    table = _table()
    try:
        table.put_item(
            Item=item,
            ConditionExpression=Attr("execution_id").not_exists(),
        )
    except ClientError as exc:
        if exc.response["Error"]["Code"] == "ConditionalCheckFailedException":
            # Row already exists — idempotent; return the id.
            return execution_id
        raise
    return execution_id


def get_execution(execution_id: str) -> dict[str, Any] | None:
    """Fetch one execution row by execution_id using a strongly-consistent read.

    Returns a plain dict (DynamoDB Item) or None if the item does not exist.
    """
    table = _table()
    resp = table.get_item(
        Key={"execution_id": execution_id},
        ConsistentRead=True,
    )
    item: dict[str, Any] | None = resp.get("Item")  # type: ignore[assignment]
    return item


def mark_running(execution_id: str) -> None:
    """Transition status queued → running.

    ConditionExpression: status must equal 'queued' (prevents double-transition).
    Swallows ConditionalCheckFailedException (already transitioned by another
    worker; not an error).

    Sets ``started_at`` to current epoch.
    """
    now_epoch = int(time.time())
    table = _table()
    try:
        table.update_item(
            Key={"execution_id": execution_id},
            UpdateExpression="SET #s = :running, started_at = :now",
            ConditionExpression=Attr("status").eq(Status.queued.value),
            ExpressionAttributeNames={"#s": "status"},
            ExpressionAttributeValues={
                ":running": Status.running.value,
                ":now": Decimal(now_epoch),
            },
        )
    except ClientError as exc:
        if exc.response["Error"]["Code"] == "ConditionalCheckFailedException":
            return
        raise


def mark_done(
    execution_id: str,
    *,
    primes: list[int],
    duration_ms: int,
) -> None:
    """Transition status running → done.

    Sets primes list, primes_count, duration_ms, completed_at, and ttl_at
    (completed_at + 30 days per TTL policy).

    ConditionExpression: status must equal 'running'.
    Swallows ConditionalCheckFailedException.
    """
    now_epoch = int(time.time())
    ttl_at = now_epoch + _TTL_DONE_DAYS * _SECONDS_PER_DAY

    # DynamoDB only accepts Decimal for numeric types.
    primes_decimal = [Decimal(p) for p in primes]

    table = _table()
    try:
        table.update_item(
            Key={"execution_id": execution_id},
            UpdateExpression="SET #s = :done, primes = :primes, primes_count = :count,"
            " duration_ms = :dur, completed_at = :now, ttl_at = :ttl",
            ConditionExpression=Attr("status").eq(Status.running.value),
            ExpressionAttributeNames={"#s": "status"},
            ExpressionAttributeValues={
                ":done": Status.done.value,
                ":primes": primes_decimal,
                ":count": Decimal(len(primes)),
                ":dur": Decimal(duration_ms),
                ":now": Decimal(now_epoch),
                ":ttl": Decimal(ttl_at),
            },
        )
    except ClientError as exc:
        if exc.response["Error"]["Code"] == "ConditionalCheckFailedException":
            return
        raise


def mark_failed(execution_id: str, *, error_message: str) -> None:
    """Transition status running → failed.

    Sets error_message, completed_at, and ttl_at (completed_at + 90 days).
    ConditionExpression: status must be 'running' (allow either running state
    to prevent orphaned rows that never got mark_running called).

    Swallows ConditionalCheckFailedException.
    """
    now_epoch = int(time.time())
    ttl_at = now_epoch + _TTL_FAILED_DAYS * _SECONDS_PER_DAY

    table = _table()
    try:
        table.update_item(
            Key={"execution_id": execution_id},
            UpdateExpression=(
                "SET #s = :failed, error_message = :err, completed_at = :now, ttl_at = :ttl"
            ),
            ConditionExpression=(
                Attr("status").eq(Status.running.value) | Attr("status").eq(Status.queued.value)
            ),
            ExpressionAttributeNames={"#s": "status"},
            ExpressionAttributeValues={
                ":failed": Status.failed.value,
                ":err": error_message,
                ":now": Decimal(now_epoch),
                ":ttl": Decimal(ttl_at),
            },
        )
    except ClientError as exc:
        if exc.response["Error"]["Code"] == "ConditionalCheckFailedException":
            return
        raise


def health_check() -> bool:
    """Probe DynamoDB reachability by describing the table.

    Returns True if the table is ACTIVE; False otherwise.
    Never raises (caller maps failure to degraded status).
    """
    try:
        endpoint_url = os.environ.get("AWS_ENDPOINT_URL")
        region = os.environ.get("AWS_DEFAULT_REGION", "eu-central-1")
        client = boto3.client(
            "dynamodb",
            endpoint_url=endpoint_url,
            region_name=region,
        )
        resp = client.describe_table(TableName=_TABLE_NAME)
        return bool(resp["Table"]["TableStatus"] == "ACTIVE")
    except Exception:  # noqa: BLE001
        return False
